import { IProduct } from "../interfaces/IProduct";

export const products: IProduct[] = [
  {
    id: 1,
    title: 'Тумбочка',
    price: 1500,
    description: 'тумбочка',
    category: 'фигня',
    image: '',
  },
  {
    id: 2,
    title: 'Молоко',
    price: 100,
    description: 'молокр',
    category: '',
    image: '',
  },
  {
    id: 3,
    title: 'Йогурт',
    price: 100,
    description: 'йогурт',
    category: 'фигня',
    image: '',
  },
  {
    id: 4,
    title: 'ПК',
    price: 40000,
    description: 'пк',
    category: 'фигня',
    image: '',
  },
  {
    id: 5,
    title: 'Чайник',
    price: 600,
    description: 'чайник',
    category: 'фигня',
    image: '',
  },
  {
    id: 6,
    title: 'Кружка',
    price: 200,
    description: 'кружка',
    category: 'фигня',
    image: '',
  },
  {
    id: 7,
    title: 'Окно',
    price: 1000,
    description: 'окно невероятное',
    category: 'фигня',
    image: '',
  },
]